repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.5
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python ]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8